services:
    nest-app:
        container_name: nest-app
        env_file:
            - ./.env
        build: .
        ports:
            - '3000:3000'
            - '3030:3030'
        environment:
            - DATABASE_HOST=postgres
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_NAME=${DATABASE_NAME}
            - EMAIL_HOST=${EMAIL_HOST}
            - EMAIL_PORT=${EMAIL_PORT}
            - EMAIL_USERNAME=${EMAIL_USERNAME}
            - EMAIL_PASSWORD=${EMAIL_PASSWORD}
        depends_on:
            - postgres
        networks:
            - app-network

    postgres:
        container_name: postgres
        env_file:
            - ./.env
        image: postgres:latest
        environment:
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - app-network

volumes:
    postgres-data:

networks:
    app-network:
        driver: bridge
